[package]
name = "challenge1_rust_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
rand = "0.8.5"
petgraph = "0.6.2"